### PR TITLE
[4279] Don't allow changing of password to same password

### PR DESCRIPTION
**Pull request by msumit**

### CODE REVIEW

**Comment by msumit** [comment]
Not sure why 2 specs are failing..

**Comment by msumit** [comment]
Dear Maintainers, 

Can we merge this PR?

Thanks,
Sumit

**Comment by 23ranjan** [comment]
+1

**Comment by rubyrider** [comment]
Opinion: 
I believe this sounds kind of unsecured when we say "Don't  allow to update with the same password", Do we need to enable this service directly? 

In case we need this feature can we make it more configurable  and make it deactivated by default?  I believe not everyone's need is same!

**Comment by georgeguimaraes** [comment]
I'm sorry but we are not accepting new behaviour into devise.

**Comment by msumit** [comment]
Not sure how its unsecured, when user already knows the correct password.. Idea behind this PR that whoever uses password archiving/expiry thing on top of devise, they have to add the same logic to enforce not same password, cause ppl just love to use same password..

**Comment by adaam2** [comment]
+1 for @msumit 

This seems like a common sense feature @georgeguimaraes

**Pull request closed without merging**
