### PR TITLE
Upgrade Mongoid to 5.0

### PR DESCRIPTION
**Pull request by yogeshjain999**
Ref : #3662

### CODE REVIEW

**Comment by josevalim** [comment]
Sorry, I thought mongoid 5 was released. I think we should not depend on the master branch for now until it is out. We can keep this open meanwhile, thank you!

**Comment by yogeshjain999** [comment]
@josevalim Ok, got your point. But Mongoid 5.0 is released. 

screenshot from 2015-12-15 18 18 57

So, should I change it to `gem "mongoid", "~> 5.0"`, instead of pointing to master ?

**Comment by josevalim** [comment]
Oh, then yes, let's point to the gem. :)

**Comment by lucasmazza** [comment]
@yogeshjain999 can you please rebase your branch with `master`? Looks like the Rails 5 merge broke some bits on your branch.

**Comment by yogeshjain999** [comment]
@josevalim @lucasmazza done. But don't understand why tests are failing now.

**Comment by lucasmazza** [comment]
I managed to run the tests locally fine - I wonder if Mongoid 5 has any issues with an outdated MongoDB server version? (Looks like Travis isn't running MongoDB 3.2).

@yogeshjain999 could you look further into that? There might be any discussions on the Travis repos about this.

**Comment by yogeshjain999** [comment]
Tests are passing locally when using **Ruby 2.2.3**, **Mongoid 5**, **Mongo 2.2.0** and **MongoDB 3.0.6**.

But they are failing locally on **Ruby 2.2.0**, with same setup as above. And, if **Mongo 2.1.1** is used, then they are passing :). Seems there is some issue with **Ruby 2.2.0** and **Mongo 2.2.0**.

Looking further into that.

**Comment by georgeguimaraes** [comment]
Hi @yogeshjain999. Did you look into that issue with Mongo 2.2.0?

**Comment by yogeshjain999** [comment]
@georgeguimaraes yes, I've looked into it. But still not able to understand why its occurring.

**Comment by ulissesalmeida** [comment]
@yogeshjain999 Could you please rebase your branch?

**Comment by yogeshjain999** [comment]
@ulissesalmeida rebased it.

**Comment by lucasmazza** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
