### PR TITLE
Add a Code of Conduct

### PR DESCRIPTION
**Pull request by FlaviaFortes**
Following the example of Rails, we might also have a Code of Conduct for this project.

### CODE REVIEW

**Comment by FlaviaFortes** [comment]
Do you guys want me to update the README, changelog or something else?

**Comment by fnando** [comment]
:+1:

**Comment by georgeguimaraes** [comment]
Now that you mentioned it, it would be great to update `CONTRIBUTING.md` as well saying that we have a CoC in this project.

**Comment by FlaviaFortes** [comment]
@georgeguimaraes Done. WDYT

**Comment by georgeguimaraes** [comment]
Nice! Merging it :+1:

**Pull request merged**
