### PR TITLE
Add GoRails resource into README.md

### PR DESCRIPTION
**Pull request by rodrigoargumedo**
This will help beginners to get started with Rails/Devise frameworks with GoRails powered by One Month. I find this resource really useful to get started and it explains in depth on how and when to implement Devise in a short amount of time at the user's discretion.

### CODE REVIEW

**Comment by excid3** [comment]
:+1: :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by carlosantoniodasilva** [comment]
Thanks for your contribution.

Even though this seems a nice resource, I am not sure it belongs to this section: it's supposed to be for people starting with authentication to know they **should not** use devise, not a devise getting started guide.

So I'd recommend either removing it and moving to the wiki, or having another section afterwards that lists it as a possible resource for getting started with devise, *after* you have done something on your own.

@josevalim thoughts?

**Comment by josevalim** [comment]
You are correct @carlosantoniodasilva . Thank you, I will revert the PR! The wiki seems to be the best place.

**Comment by rodrigoargumedo** [comment]
I don't really mind going into the wiki but I reconsidered that it should of been on the Wiki. @carlosantoniodasilva @josevalim

**Comment by carlosantoniodasilva** [comment]
:+1:

**Pull request merged**
