### PR TITLE
generate a confirmation_token over an empty string

### LINKED ISSUE #5071: Confirmable should generate a token if confirmation_token is currently an empty string
## Environment

- Ruby 2.5.5p157
- Rails 5.2.3
- Devise 4.6.1

## Current behavior

Currently, when using the confirmable module, devise only checks if the `confirmation_token` field not nil. If it's nil, it will generate a confirmation token for you; if it's not, it won't. However, it can be set to an empty string, which should not be allowed, as it presents a security issue, allowing someone passing an empty string as the confirmation token to sign in as the person with the blank string confirmation token. 

This is the offending code: https://github.com/plataformatec/devise/blob/e91b8ee0bac0503af119bf7333499d7729166a4d/lib/devise/models/confirmable.rb#L249

## Expected behavior

Devise should do something like `if self.confirmation_token.present?`, which checks for nil and blank.

### PR DESCRIPTION
**Pull request by ajsharp**
Fixes #5071

### CODE REVIEW

**Comment by ajsharp** [comment]
@mracos Any thoughts here? This should probably be considered a security issue, as it allows anyone to access the system with an empty token.

**Comment by mracos** [comment]
Sorry @ajsharp, I've been really busy with work lately, so I didn't have much time to take a deeper look at this but will try to give you some feedback in the next days.
Thanks!

**Comment by amangano-privy** [comment]
Would it be possible to add a validation to prevent the model from being saved when confirmation_token is an empty string?

**Comment by tegon** [comment]
@ajsharp Thanks for your contribution!

I was digging into this, and a better approach for us is to ensure it's not possible to confirm a user with a blank `confirmation_token` parameter - i.e. to return a validation error inside the `ConfirmationsController#show` [action](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/confirmations_controller.rb#L22).
That should be enough to ensure no "invalid" records will be confirmed by mistake.

As for the `confirmation_token` being set to blank, that doesn't seem to be possible with the current code we have. I'm assuming something else could've happened in the system to let the records in that state. Unless we find a real case where Devise is setting the token to a blank string, I think it's not worth it to include more code to handle this.

@amangano-privy I thought about adding the validation, but we can't always require this field, so we would need a context validation. That would only protect the model against the known use cases. Another thing to take into account is that a bunch of places inside Devise uses `validate: false`.
So I think the validation wouldn't add that much value. The current code is already generating the token in a `before_create` callback, so I'm guessing it would require some external action to leave the field with a blank string - instead of `nil`.

WDYT you think? Thoughts?

**Comment by tegon** [comment]
Closed in favor of https://github.com/plataformatec/devise/pull/5132

**Pull request closed without merging**
