### PR TITLE
Just use regular 4.x mongoid gem

### PR DESCRIPTION
**Pull request by vincentwoo**
Hopefully this PR makes tests green again.

### CODE REVIEW

**Comment by carlosantoniodasilva** [comment]
I suppose we could just add the mongo repo as well, but that works too, at least for now. Thanks!

**Comment by yogeshjain999** [comment]
@carlosantoniodasilva tests are failing for Mongoid 5.0 because, `test/support/mongoid.yml` is expecting `clients` instead of `sessions`. Why can't we replace it ?

**Comment by josevalim** [comment]
We can likely define both eys?

**Comment by yogeshjain999** [comment]
Yes, we can do that too, by checking Mongoid version.

**Pull request merged**
