### PR TITLE
Update confirmable_test.rb

### PR DESCRIPTION
**Pull request by bogdanvlviv**

### CODE REVIEW

**Comment by josevalim** [comment]
Rationale please? :)

**Comment by bogdanvlviv** [comment]
if confirmation sent to user,** it is mean that he is created** and we don't know what we will be or we are have in `active_for_authentication?` method. if there is  `persisted?` method be or will be?

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by bogdanvlviv** [comment]
Could you give me answers to the question in pull request https://github.com/plataformatec/devise/pull/3933 and  what you think about this pull request? a have a free time, now and i will be happy to spend it for "making devise more flexible" ;)

**Pull request merged**
