### PR TITLE
Send dedicated reconfirmation email

### PR DESCRIPTION
**Pull request by akavinash1994**

### CODE REVIEW

**Comment by saiqulhaq** [comment]
this PR is same as https://github.com/plataformatec/devise/pull/4846

**Comment by akavinash1994** [comment]
@saiqulhaq 
@tegon commented on [#4145](https://github.com/plataformatec/devise/issues/4145) that 
`The other pull request had many conflicts and I didn't get a response when I asked for a rebase.
If anyone else wants to open a new one with a similar implementation, feel free to.`
thats why I raised this PR

**Comment by saiqulhaq** [comment]
@akavinash1994 yes, but in newest discussion https://github.com/plataformatec/devise/pull/4846, @tegon preferred to add specific email for reconfirmation

**Comment by tegon** [comment]
Exactly, the PR I was talking about is this one https://github.com/plataformatec/devise/pull/4182.
That's the implementation we should follow, IMO.

**Pull request closed without merging**
