### PR TITLE
Refactor `Rememberable#serialized_in_cookie?` to split class/instance API

### PR DESCRIPTION
**Pull request by lucasmazza**
An alternative API to deal with the `serialize_from_cookie_with_or_without_record` pile of responsibilities. /cc @josevalim

### CODE REVIEW

**Comment by josevalim** [comment]
I don't like that we are a using a serialized_in_cookie? in the instance. Can we find a better name? Maybe `remember_active?` or something of sorts. Also, I wouldn't pass the ID in. So I would go with something like `remember_active?(token, generated_at)`. Thoughts?

**Comment by lucasmazza** [comment]
> Maybe remember_active? or something of sorts.

:+1:

> So I would go with something like remember_active?(token, generated_at). Thoughts?

We could do that, and it would help to move the cookie Time serialization handling outside of the model. The only downside here is that the "cookie splatting" logic will move away from the method that generates the cookie (`serialize_into_cookie`), but maybe that isn't so bad as one might consider.

**Comment by josevalim** [comment]
@lucasmazza  the cookie splatting logic is only needed for backwards compatibility. so it is ok to be a bit ugly for now, we can leave a todo and remove it in future versions.

**Comment by lucasmazza** [comment]
@josevalim pushed a new commit, how does it look?

**Comment by josevalim** [comment]
Beautiful  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
