### PR TITLE
Raise error if no ORM is found during install generator

### PR DESCRIPTION
**Pull request by arjunsharma**
This is my stab at fixing #3800. I'm happy to keep working on this if you have feedback, I've used Devise on many projects and figured I would try and do my part to contribute.

Thanks!

Arjun

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @arjunsharma! I think we should also check if `ActiveRecord` is defined or not. If it is defined, then we should not raise. :)

**Comment by josevalim** [comment]
Ignore me. The patch seems fine as is. :) Thank you!

**Comment by arjunsharma** [comment]
Awesome!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
