### PR TITLE
Add ActiveSupport::Notification instruments

### PR DESCRIPTION
**Pull request by BM5k**
I've started adding support for ActiveSupport::Notification instruments to devise. Before I get too carried away, I'd like to know if this approach is satisfactory, and if there are any specific places that should emit notifications.

Also, test_unit isn't exactly my cup of tea, so I could use some pointers in how to test these instruments, if that's necessary.

This is still a work in progress.

### CODE REVIEW

**Comment by josevalim** [comment]
Ping. :)

**Comment by BM5k** [comment]
Oops! I’ve been super distracted with other stuff and kind of forgot about this. I’ll set some time aside for it this week and see what I can get finished.

**Comment by BM5k** [comment]
It seems like another good time for a sanity check. Am I still headed in the right direction with this?

Does anyone else have thoughts about where instrumentation should occur? I’ve been mainly just reading through the code and guestimating.

**Comment by ulissesalmeida** [comment]
@lucasmazza  @josevalim  Do we have to add any new instrumentations? It will launch after `4.0.0` release right?

**Pull request closed without merging**
