### PR TITLE
Set minimum password length for edit and new views

### PR DESCRIPTION
**Pull request by Yanchek99**
Address issue #3967

### CODE REVIEW

**Comment by ulissesalmeida** [comment]
@Yanchek99 I think would be cool put a similar message on form like the [`new` form](https://github.com/plataformatec/devise/blob/master/app/views/devise/registrations/new.html.erb#L13). What do you think?

**Comment by Yanchek99** [comment]
@ulissesalmeida I agree, however I am not sure a good place to put it because there is also the "(leave blank if you don't want to change it)" message. Perhaps under the text field?

**Comment by ulissesalmeida** [comment]
@Yanchek99 👍

**Comment by Yanchek99** [comment]
@ulissesalmeida updated, with suggestions.

**Comment by ulissesalmeida** [comment]
@Yanchek99 Looking good! Thanks!

**Comment by lucasmazza** [comment]
@Yanchek99 thanks!

**Comment by mizurnix** [comment]
Hi, I think I found a small problem regarding this feature. minimum_password_length is accessible in registrations/edit view, but only if the form is submitted without errors.

User goes to registrations/edit page and it's there:

image 7

User submits incomplete form and after the redirect, it's no longer there:

image 8

This is a vanilla devise installation (I only copied views, did not change any of them): http://testdevisepasswordlength.herokuapp.com/

Do you guys agree this should be fixed? If yes, should I open a new issue?

**Comment by ethirajsrinivasan** [comment]
@mizurnix can you provide the source code for your application

**Comment by mizurnix** [comment]
@ethirajsrinivasan https://github.com/mizurnix/test_devise_passwrod_length

**Comment by ethirajsrinivasan** [comment]
@mizurnix  #4343 Created PR to solve the same. @lucasmazza Please have a look

**Pull request merged**
