### PR TITLE
Added validation check to registrations#create

### PR DESCRIPTION
**Pull request by wazery**
I have added a validation check before saving the resource, because in my applications I noticed that there are huge ID gapes that happens regularly because some users not passing the validation checks and the save is called in which it increments the ID but the validation failure rolls back the transaction leaving the incremented ID. Please review that scenario and let me know if my PR can be merged.

### CODE REVIEW

**Comment by josevalim** [comment]
save should validate your resource. We should not need to call `valid?` directly.

**Comment by josevalim** [comment]
And thanks for the pull request! :D Which ORM are you using btw?

**Comment by wazery** [comment]
ActiveRecord

**Comment by josevalim** [comment]
Yup, so save should definitely do it, we
Shouldn't check it ourselves!


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by wazery** [comment]
So any idea why the ID gaps happen?

**Comment by josevalim** [comment]
No, I don't know. But I wouldn't worry about it either. It may be a callback aborting the operation?

**Pull request closed without merging**
