### PR TITLE
issue 4526 adds skip email and password change notifications methods

### PR DESCRIPTION
**Pull request by iorme1**
I added methods to skip email change notifications and password change notifications on per edit basis like the issue was requesting.  I also added tests for these two methods.  All the tests are passing and the functionality worked when I tried it out on my test app.  This is my first PR so please let me know if I missed conforming to any guidelines or if I need to improve or adjust the code to fit your structure better. Thanks!

### CODE REVIEW

**Comment by iorme1** [comment]
I just noticed on my first test I accidentally put "send_email_changed_notification: true do..." instead of "send_password_change_notifications: true do...". I'll fix that up...please let me know if anything else needs fixing.

**Comment by tegon** [comment]
@iorme1 I forgot this one, sorry about that 😞  
There are many PRs to keep track here, but yours is going to be reviewed, for sure.

**Comment by feliperenan** [comment]
@iorme1 We could document this new feature in somewhere in our README, though I don't know the better place. Maybe after this section https://github.com/plataformatec/devise#password-reset-tokens-and-rails-logs? 🤔

**Comment by iorme1** [comment]
Sounds great, I will implement these changes within the next couple of days. Thanks for the feedback!

**Comment by ZachYench** [comment]
Hey, I was wondering if this is close to being done?

**Comment by tegon** [comment]
I'll take a look at the PR this week.

**Comment by tegon** [comment]
@ZachYench Thanks for this! Sorry for taking so long to review it, I got stuck with other things and wasn't able to review it before 😞

**Pull request merged**
