### PR TITLE
Added DeviseController#set_flash_message!

### PR DESCRIPTION
**Pull request by oss92**
* Introduced `DeviseController.set_flash_message!` for conditional flash messages setting to reduce method complexity.

* Reduced complexity of `DeviseHelper#devise_error_messages!` and `Devise::FailureApp#scope_url`.

* `DeviseHelper#devise_error_messages_html` not only reduces complexity but also makes error messages easier to override by developers who want to change styling of error message.

* Changed `confirm!` to `confirm` in tests.

### CODE REVIEW

**Comment by lucasmazza** [comment]
I dig the `set_flash_message!` and internal reorganisation of `scope_url` but I'm not too keen on the addition of devise_error_messages_html` and `generate_url`. They might push some of the complexity outside of their methods to new ones but they might new not-exactly-public APIs that we probably don't want to support and let developers to override it.

@josevalim @carlosantoniodasilva any thoughts on this?

**Comment by josevalim** [comment]
I agree with the changes but we need to #:nodoc: the new methods exactly so users do not consider them to be part of our API.

**Comment by oss92** [comment]
Added #:nodoc: to new methods.

**Comment by carlosantoniodasilva** [comment]
My 2 cents: I kinda agree with @lucasmazza on this one, the flash message extraction and the internal refactorings inside the methods in general look good, but I'd rather not introduce extra methods for the sake of reducing complexity. It might make code climate happier, but it might also feel that reading the code gets harder.

Thank you for your contribution @oss92! :heart:

**Comment by oss92** [comment]
Ok so should I remove `generate_url` and `devise_error_messages_html` to make this PR ready?

And you are welcomed :+1: I pretty much use devise in ALL of my Rails applications and I should start contributing to it :100:

**Comment by lucasmazza** [comment]
> Ok so should I remove generate_url and devise_error_messages_html to make this PR ready?

Yes, please - and rebase your branch against `master` as it show that there are some conflicts to be solved. Thanks!

**Comment by oss92** [comment]
Done @lucasmazza

**Pull request merged**
