### PR TITLE
Devise + Mongoid store wrong data in session

### PR DESCRIPTION
**Pull request by hauleth**
I'm using Devise 3.2.3 + Mongoid 4.0.0.beta1 and when I try to call `current_user` I get:

~~~
The operation: #<Moped::Protocol::Query
  @length=125
  @request_id=18
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="orodruin_development.users"
  @skip=0
  @limit=-1
  @selector={"$query"=>{"_id"=>{"$oid"=>BSON::ObjectId('530a1ec84e49550fbd000000')}}, "$orderby"=>{:_id=>1}}
  @fields=nil>
failed with error 10068: "invalid operator: $oid"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.
~~~

Bug is somewhere where this is set:

    warden.user.user.key: [[{"$oid"=>BSON::ObjectId('530a1ec84e49550fbd000000')}], "$2a$10$/J1DMorvMdGZm6aQicsYL."]

### CODE REVIEW

**Comment by arthurnn** [comment]
:heart:

**Comment by arthurnn** [comment]
Just fixed this bug on Mongoid side https://github.com/mongoid/mongoid/commit/658a5d4e55e0ff94fb89fa1e7b970edcc7c4283d , it will be included in the next release , 4.0.2
thanks all

**Comment by almnes** [comment]
@arthurnn any specific date on when 4.0.2 will be released?

**Comment by arthurnn** [comment]
@almnes , soon, probably today or tomorrow.

**Comment by josevalim** [comment]
Ping for a 4.0.2 release. :)

**Comment by arthurnn** [comment]
done https://rubygems.org/gems/mongoid/versions/4.0.2

**Comment by josevalim** [comment]
Obrigado!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by miguelgraz** [comment]
I know I'm late to the party here but just wanted to say thanks to everyone on this thread, I have a case where I have some data migrated from Postgres and therefore some records with integer IDs and other with ObjectID IDs, the information here helped me put together this little hack that fixed my problem, on my `User` model:
``` ruby
  def self.serialize_from_session(key, salt)
    record = to_adapter.get(key[0])
    record ||= to_adapter.get(key[0].to_i)
    record if record && record.authenticatable_salt == salt
  end
```

**Pull request merged**
