### PR TITLE
set_flash_method! instead of set_flash_method in omniauth callbacks controller

### PR DESCRIPTION
**Pull request by saichander17**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request. Can you explain why we need this change?

**Comment by tegon** [comment]
Hello @saichander17, thanks for your pull request.
Would you mind telling us the motivation behind it?

**Comment by KelseyDH** [comment]
Would this finally be a solution to https://github.com/plataformatec/devise/issues/4275 ?

**Comment by rafaelfranca** [comment]
This doesn't change anything related to #4275. I mean, it doesn't try to access the flash message if you don't request using a navigational format, but if you do you will get the same problem. The right way to fix #4275 is to not do a HTML request (navigational) in a API application, like the two updates in the issue description shows.

**Comment by KelseyDH** [comment]
@rafaelfranca  Thanks for responding.  While I get that its not ideal for a Rails API to serve HTML, with `devise_token_auth` I struggle to see how there is any other way of doing a password reset.

As I added to this [mega thread of people pulling their hair out trying to get a sane password reset system working with devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth/issues/604#issuecomment-351180401), an API Rails-only email password reset flow doesn't work if the client apps that need to be opened from a password reset link sent by email are iOS and Android:  custom app scheme redirects are blocked by Gmail, and it appears the proper solution to getting around this is to handle these scheme redirects [within an app endpoint first, to get around Gmail's stripping of custom scheme URL's.](https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/81#issuecomment-97701155)

So in light of how Google treat's custom scheme URL's in password resets... I am unsure of how I can achieve a seemless password reset redirect to a mobile app without serving some form of HTML page from my Rails API.  (When you look at app's like Slack, or any other app where there is a custom app scheme redirect from an email, it's almost always done via a link that first goes to an app-generated HTML page first.)

On password reset email links `devise_token_auth` users seem caught in a catch 22:  don't use html and have their iOS/android custom app scheme URL's break in gmail, or add devise to get a web form for their password reset portion of their app, and have it completely break when using Rails api due to design decisions made by `devise`.

(Any advice on solving this would be much appreciated!!)

**Comment by rafaelfranca** [comment]
If you are rendering HTML you Rails application can't be an API-only application anymore. You application now need flash, sessions, CSRF protection, etc. As your application now needs to render html. I'd recommend you to use `ActionController::Base` instead of `ActionController::API` as the superclass of you reset password controller. Doing that you will have the `flash` method again and that code will not raise.

**Comment by KelseyDH** [comment]
@rafaelfranca   Thank you, subclassing my controllers to create two ApplicationControllers, one renamed to `ApiController` pointing to Rails API as `ApiController < ActionController::Api`, and the other to `ApplicationController < ActionController::Base`, appears to have allowed me to get devise html up and running.  (Though not sure if doing this is a bad idea or may produce unknown side effects.)

**Pull request merged**
