### PR TITLE
Fix syntax for MRI 2.5.0-preview1.

### PR DESCRIPTION
**Pull request by pat**
This ensures the tests are green when run on MRI 2.5.0-preview1 :)

### CODE REVIEW

**Comment by timoschilling** [comment]
:+1:

**Comment by nashby** [comment]
@pat thanks!

**Comment by redtachyons** [comment]
Any ETA for releasing this fix. Devise isn't working with ruby 2.5.0

**Comment by wbotelhos** [comment]
Just for information, @tegon , this fix is not listed on `Unreleased` section of `CHANGELOG.md`.

For now can use master @redtachyons :

```
gem 'devise', github: 'plataformatec/devise', ref: 'HEAD' 
```

**Comment by tegon** [comment]
@wbotelhos Thanks for noticing, I've added to the `CHANGELOG.md`.

I've also released version [4.4.0](https://rubygems.org/gems/devise/versions/4.4.0) with the fix.

**Comment by PolymathWhiz** [comment]
Nice

**Pull request merged**
