### PR TITLE
 rememberable and timeoutable should work together

### LINKED ISSUE #4778: timeout and rememberable
Why was the timeout and rememberable compatibility removed?

```ruby
def timedout?(last_access)
    return false if remember_exists_and_not_expired?
```

https://github.com/plataformatec/devise/blob/master/lib/devise/models/timeoutable.rb#L30
(removed in commit https://github.com/plataformatec/devise/commit/4ec7dc0f2777bde10125dcf6f72c536232086665)

## Current behavior

Timeout and Rememberable do not work together. The shorter one overrules the longer one.

## Expected behavior

I would expect rememberable to control sessions via cookie, while timeoutable can still control session time without cookies. (This is both relevant for http, where cookies are disabled on `secure: true`, as well as for users who explicitly choose not to select remember me).

At the moment, when I want to use rememberable, I have not control what so ever on session time, just on the session cookie expiration time.

### PR DESCRIPTION
**Pull request by fladson**
I took the liberty to fix the comments at #4926 and send as a new PR since that is inactive for days.
I hope that's ok with you @prithvi16

Fixes #4778

### CODE REVIEW

**Comment by fladson** [comment]
@tegon Could you review that again and retry the build please?

**Comment by feliperenan** [comment]
Hi @fladson, thanks for the pull-request.

Are you able to reproduce this issue? because we aren't, see: https://github.com/plataformatec/devise/issues/4778#issuecomment-465718626.

**Comment by prithvi16** [comment]
Thanks,  @fladson for the PR.  Sorry, I have been occupied with work and could not push any changes.

**Comment by fladson** [comment]
@feliperenan I haven't tried to reproduce it actually but that's ok, you can close both PRs if you feel that this isn't needed anymore.

**Pull request closed without merging**
