### PR TITLE
Rails 5.1

### PR DESCRIPTION
**Pull request by jcoyne**
Updated #4444 to use a final release of Rails 5.1

### CODE REVIEW

**Comment by Ixalion** [comment]
Any timeline on when this will be accepted?

**Comment by tomekr** [comment]
Hi, I did a clean install of Rails 5.1. with Devise and it looks like the responders gem is installing an old version as well. `Gemfile.lock` looks like:

~~~
GIT
  remote: https://github.com/jcoyne/devise.git
  revision: 7c4e8c8d17047bceea490173af42bfbbc54cf849
  branch: rails-5.1
  specs:
    devise (4.2.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.2)
      responders
      warden (~> 1.2.3)
...
    responders (0.6.5)
~~~

The current version is `2.3.0`. This then causes a `mimes_for_respond_to` error to occur when trying to request Devise endpoints.

**Comment by jcoyne** [comment]
@tomekr It's getting an old version because we're waiting on a release of the responders gem too. See https://github.com/plataformatec/responders/issues/179

**Comment by lrosskamp** [comment]
my `Gemfile.lock` looks like this. I'm using Rails 5.1 and `gem 'devise'`
`devise (1.5.4)`

**Comment by tomekr** [comment]
@jcoyne ahh good call, added `gem "responders", git: 'https://github.com/plataformatec/responders.git', branch: 'master'` for now and it looks like that fixed the issue.

@lrosskamp as a temporary solution until these PR's are merged is to add the following to my Gemfile:

~~~
gem 'devise', git: 'https://github.com/jcoyne/devise.git', branch: 'rails-5.1'
gem "responders", git: 'https://github.com/plataformatec/responders.git', branch: 'master'
~~~

**Comment by davidmccoy** [comment]
Thanks @jcoyne!

**Comment by lrosskamp** [comment]
thanks @jcoyne but I get this error:
```https://github.com/plataformatec/responders.git (at master@153f2c6) is not yet checked out. Run `bundle install` first.```

running `bundle install` doesn't fix it. Do you know what may have cause this?

**Comment by christophermlne** [comment]
@lrosskamp looks like the branch `jcoyne:rails-5.1` was deleted

**Pull request merged**
